### ISSUE TITLE
Vertaisarviointi 12.4.2021

### ISSUE THREAD

**Issue by ajperttula** [federma/tsoha-recipes#1]
Sivuston ulkoasu on selkeä ja toiminnot löytää helposti.

Parannuksia voisi olla esim:
- Voisi harkita, että kirjautumista vaativat toiminnot eivät näy kirjautumatta (kommentointi/reseptin lisäys)
- Kirjautuneena olon näkisi suoraan yläbannerista menemättä Käyttäjä-sivulle

Huomioita reseptisivusta:
- Kommentin lisäysaika näyttäisi olevan utc ajassa? (-3 Suomen aikaan)

Kehitysehdotuksia:
- Etusivun reseptien lajittelu, uusimmat, vanhimmat, katsotuimmat?
- Oman reseptin muokkaus/poistomahdollisuus (kuten olit readme:ssä maininnut)

Itse teen myös reseptisovellusta ja ajattelin tehdä toimminnon, jossa annoskokoa voisi muuttaa ja määrät muuttuisivat vastaavasti. Päädyin kuitenkin toteuttamaan ainesosien lisäämisen yhtenä kenttänä, koska kuten itsekin totesit, kaikkien ainesten määrää on resepteissä vaikea määritellä.

Tietokanta:
- Selkeä jaottelu ja viittaukset

HTML-koodi:
- Selkeältä vaikuttaa. css- ja bootstrap-asioita en osaa kommentoida, koska en ole vielä päässyt omassa projektissani ulkoasun suunnitteluun
- 4 merkin sisennys vie koodin paikoitellen melko oikealle, mutta tämä on nyt ihan makuasia.

Python:
- Kuten mainitsit, syötteiden tarkastus uupuu vielä, sekä csrf-tarkistukset lomakkeissa.
- Koodi on jaoteltu selkeästi omiin moduuleihin ja vaikuttaisi olevan suht tiivistä.
- recipes.py enter funktiossa mainittu bugi: auttaisiko, jos loopissa jokaiselle itemille olisi try/except lohkot? Esim. määrä-kenttään, kun kirjoittaa tekstiä eikä numeroita, niin silloinhan tuo feilaa.

Kokonaisuutena projekti on mielestäni hyvällä mallilla ja koodisi on selkeää. Hienoa työtä!

**Comment by federma** [comment]
Kiitos huomioista! Tarkoitus olisi varmaan aika lailla kaikki nuo parannukset ja kehitykset toteuttaa, mutta täytyy katsoa riittääkö kurssin tunnit kaikkeen.

Onpa hauska, että teet vastaavaa sovellusta. Täytyy seurailla miten etenee :)
