### ISSUE TITLE
Vertaisarvointi

### ISSUE THREAD

**Issue by mcdongo** [federma/tsoha-recipes#2]
Yleiskuva ja sovelluksen testaus:
- Sovelluksen ulkoasu on todella siisti ja sovellusta on miellyttävä käyttää
- En löytänyt ongelmia sovelluksestasi ja ominaisuudet, jotka ilmoitit toimivat
- README-tiedosto on riittävän kuvaava ja olennaiset ominaisuudet on listattu

Koodi ja tietokanta:
- Koodi on siistiä, jaettu järkevästi eri metodeihin ja tiedostoihin tehtävien mukaan
- Koodissa ei ole toistoa
-  Koodissa on noudatettu hyvin periaatetta, että yksi metodi tekee varsinaisesti yhtä asiaa
- SQL-kyselyt on totetutettu järkevästi, ei ole "turhia kyselyitä" ja kaikki tieto on pyritty hakemaan mahdollisimman pienellä määrällä kyselyitä
- SQL-injektiota varten on varauduttu asianmukaisesti antamalla tiedot SQL-kyselyhin muuttujina
- Projektille arkaluontoisia tietoja ei löydy hakemistosta (.env -tiedosto) tai koodin sisältä (käytetty getenv-metodia)
- Tietokanta on toteutettu järkevästi:
- Tieto tietokannassa on atomista
- Tietokannassa ei ole ns. "turhaa" tietoa
- Tietokanta ei toista itseään
- Pidin ratkaisustasi toteuttaa koodin sisällä SQL-kysely reseptien järjestyksen vaihtamiseen

Hyvää jälkeä. Mielestäni kyseessä on hyvin selkokäyttöinen ja oikeasti käytännössä hyödyllinen sovellus. En keksi nipotettavaa työstä, joka on toteutettu näin hyvin. Tietysti esimerkiksi CSRF-haavoittuvuudelle voisi tehdä jotain, mutta niin mainitset tekeväsi myöhemmin README-tiedostossa. Hyvää työtä.

**Comment by federma** [comment]
Kiitos arvioinnista ja hyvistä huomioista! CSRF-haavoittuvuus on tosiaan tarkoitus vielä tilkitä, tehdä syötteentarkistuksia myös Pythonille ja viilata vähän toiminnallisuutta ja ulkoasua.
